# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is autogenerated

from deye_sensor import SingleRegisterSensor, ComputedPowerSensor, DoubleRegisterSensor, ComputedSumSensor, SensorRegisterRange

deye_sg04lp3_solar_672 = SingleRegisterSensor('PV1 Power', 672, 1,
                                              mqtt_topic_suffix='dc/pv1/power',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_673 = SingleRegisterSensor('PV2 Power', 673, 1,
                                              mqtt_topic_suffix='dc/pv2/power',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_676 = SingleRegisterSensor('PV1 Voltage', 676, 0.1,
                                              mqtt_topic_suffix='dc/pv1/voltage',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_678 = SingleRegisterSensor('PV2 Voltage', 678, 0.1,
                                              mqtt_topic_suffix='dc/pv2/voltage',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_677 = SingleRegisterSensor('PV1 Current', 677, 0.1,
                                              mqtt_topic_suffix='dc/pv1/current',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_679 = SingleRegisterSensor('PV2 Current', 679, 0.1,
                                              mqtt_topic_suffix='dc/pv2/current',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_529 = SingleRegisterSensor('Daily Production', 529, 0.1,
                                              mqtt_topic_suffix='day_energy',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_solar_534 = DoubleRegisterSensor('Total Production', 534, 0.1,
                                              mqtt_topic_suffix='total_energy',
                                              groups=['deye_sg04lp3'])

deye_sg04lp3_battery_514 = SingleRegisterSensor('Daily Battery Charge', 514, 0.1,
                                                mqtt_topic_suffix='battery/daily_charge',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_515 = SingleRegisterSensor('Daily Battery Discharge', 515, 0.1,
                                                mqtt_topic_suffix='battery/daily_discharge',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_516 = DoubleRegisterSensor('Total Battery Charge', 516, 0.1,
                                                mqtt_topic_suffix='battery/total_charge',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_518 = DoubleRegisterSensor('Total Battery Discharge', 518, 0.1,
                                                mqtt_topic_suffix='battery/total_discharge',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_590 = SingleRegisterSensor('Battery Power', 590, 1,
                                                mqtt_topic_suffix='battery/power',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_587 = SingleRegisterSensor('Battery Voltage', 587, 0.01,
                                                mqtt_topic_suffix='battery/voltage',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_588 = SingleRegisterSensor('Battery SOC', 588, 1,
                                                mqtt_topic_suffix='battery/soc',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_591 = SingleRegisterSensor('Battery Current', 591, 0.01,
                                                mqtt_topic_suffix='battery/current',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_battery_586 = SingleRegisterSensor('Battery Temperature', 586, 0.1,
                                                mqtt_topic_suffix='battery/temperature',
                                                groups=['deye_sg04lp3_battery'])

deye_sg04lp3_grid_625 = SingleRegisterSensor('Total Grid Power', 625, 1,
                                             mqtt_topic_suffix='ac/total_power',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_598 = SingleRegisterSensor('Grid Voltage L1', 598, 0.1,
                                             mqtt_topic_suffix='ac/l1/voltage',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_599 = SingleRegisterSensor('Grid Voltage L2', 599, 0.1,
                                             mqtt_topic_suffix='ac/l2/voltage',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_600 = SingleRegisterSensor('Grid Voltage L3', 600, 0.1,
                                             mqtt_topic_suffix='ac/l3/voltage',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_520 = SingleRegisterSensor('Daily Energy Bought', 520, 0.1,
                                             mqtt_topic_suffix='ac/daily_energy_bought',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_522 = DoubleRegisterSensor('Total Energy Bought', 522, 0.1,
                                             mqtt_topic_suffix='ac/total_energy_bought',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_521 = SingleRegisterSensor('Daily Energy Sold', 521, 0.1,
                                             mqtt_topic_suffix='ac/daily_energy_sold',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_524 = DoubleRegisterSensor('Total Energy Sold', 524, 0.1,
                                             mqtt_topic_suffix='ac/total_energy_sold',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_grid_524 = DoubleRegisterSensor('Total Grid Production', 524, 0.1,
                                             mqtt_topic_suffix='ac/total_energy_sold',
                                             groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_630 = SingleRegisterSensor('Current L1', 630, 0.01,
                                                 mqtt_topic_suffix='ac/l1/current',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_631 = SingleRegisterSensor('Current L2', 631, 0.01,
                                                 mqtt_topic_suffix='ac/l2/current',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_632 = SingleRegisterSensor('Current L3', 632, 0.01,
                                                 mqtt_topic_suffix='ac/l3/current',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_633 = SingleRegisterSensor('Inverter L1 Power', 633, 1,
                                                 mqtt_topic_suffix='ac/l1/power',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_634 = SingleRegisterSensor('Inverter L2 Power', 634, 1,
                                                 mqtt_topic_suffix='ac/l2/power',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_635 = SingleRegisterSensor('Inverter L3 Power', 635, 1,
                                                 mqtt_topic_suffix='ac/l3/power',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_inverter_540 = SingleRegisterSensor('DC Temperature', 540, 0.1,
                                                 mqtt_topic_suffix='radiator_temp',
                                                 groups=['deye_sg04lp3'])

deye_sg04lp3_sensors = [
    deye_sg04lp3_solar_672,
    deye_sg04lp3_solar_673,
    deye_sg04lp3_solar_676,
    deye_sg04lp3_solar_678,
    deye_sg04lp3_solar_677,
    deye_sg04lp3_solar_679,
    deye_sg04lp3_solar_529,
    deye_sg04lp3_solar_534,
    deye_sg04lp3_battery_514,
    deye_sg04lp3_battery_515,
    deye_sg04lp3_battery_516,
    deye_sg04lp3_battery_518,
    deye_sg04lp3_battery_590,
    deye_sg04lp3_battery_587,
    deye_sg04lp3_battery_588,
    deye_sg04lp3_battery_591,
    deye_sg04lp3_battery_586,
    deye_sg04lp3_grid_625,
    deye_sg04lp3_grid_598,
    deye_sg04lp3_grid_599,
    deye_sg04lp3_grid_600,
    deye_sg04lp3_grid_520,
    deye_sg04lp3_grid_522,
    deye_sg04lp3_grid_521,
    deye_sg04lp3_grid_524,
    deye_sg04lp3_grid_524,
    deye_sg04lp3_inverter_630,
    deye_sg04lp3_inverter_631,
    deye_sg04lp3_inverter_632,
    deye_sg04lp3_inverter_633,
    deye_sg04lp3_inverter_634,
    deye_sg04lp3_inverter_635,
    deye_sg04lp3_inverter_540
]

deye_sg04lp3_register_ranges = [
    SensorRegisterRange(group='deye_sg04lp3_battery', first_reg_address=514, last_reg_address=558),
    SensorRegisterRange(group='deye_sg04lp3', first_reg_address=514, last_reg_address=558),
    SensorRegisterRange(group='deye_sg04lp3_battery', first_reg_address=586, last_reg_address=591),
    SensorRegisterRange(group='deye_sg04lp3', first_reg_address=598, last_reg_address=636),
    SensorRegisterRange(group='deye_sg04lp3', first_reg_address=672, last_reg_address=679)
]

