# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# This file is autogenerated

# flake8: noqa

from deye_sensor import (
    SingleRegisterSensor,
    ComputedPowerSensor,
    DoubleRegisterSensor,
    ComputedSumSensor,
    SensorRegisterRange,
)

deye_sg04lp3_solar_672 = SingleRegisterSensor(
    "PV1 Power", 672, 1, mqtt_topic_suffix="dc/pv1/power", unit="W", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_673 = SingleRegisterSensor(
    "PV2 Power", 673, 1, mqtt_topic_suffix="dc/pv2/power", unit="W", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_676 = SingleRegisterSensor(
    "PV1 Voltage", 676, 0.1, mqtt_topic_suffix="dc/pv1/voltage", unit="V", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_678 = SingleRegisterSensor(
    "PV2 Voltage", 678, 0.1, mqtt_topic_suffix="dc/pv2/voltage", unit="V", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_677 = SingleRegisterSensor(
    "PV1 Current", 677, 0.1, mqtt_topic_suffix="dc/pv1/current", unit="A", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_679 = SingleRegisterSensor(
    "PV2 Current", 679, 0.1, mqtt_topic_suffix="dc/pv2/current", unit="A", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_529 = SingleRegisterSensor(
    "Daily Production", 529, 0.1, mqtt_topic_suffix="day_energy", unit="kWh", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_solar_534 = DoubleRegisterSensor(
    "Total Production", 534, 0.1, mqtt_topic_suffix="total_energy", unit="kWh", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_battery_514 = SingleRegisterSensor(
    "Daily Battery Charge",
    514,
    0.1,
    mqtt_topic_suffix="battery/daily_charge",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_battery_515 = SingleRegisterSensor(
    "Daily Battery Discharge",
    515,
    0.1,
    mqtt_topic_suffix="battery/daily_discharge",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_battery_516 = DoubleRegisterSensor(
    "Total Battery Charge",
    516,
    0.1,
    mqtt_topic_suffix="battery/total_charge",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_battery_518 = DoubleRegisterSensor(
    "Total Battery Discharge",
    518,
    0.1,
    mqtt_topic_suffix="battery/total_discharge",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_battery_590 = SingleRegisterSensor(
    "Battery Power", 590, 1, mqtt_topic_suffix="battery/power", unit="W", signed=True, groups=["deye_sg04lp3_battery"]
)

deye_sg04lp3_battery_587 = SingleRegisterSensor(
    "Battery Voltage",
    587,
    0.01,
    mqtt_topic_suffix="battery/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_battery_588 = SingleRegisterSensor(
    "Battery SOC", 588, 1, mqtt_topic_suffix="battery/soc", unit="%", signed=False, groups=["deye_sg04lp3_battery"]
)

deye_sg04lp3_battery_591 = SingleRegisterSensor(
    "Battery Current",
    591,
    0.01,
    mqtt_topic_suffix="battery/current",
    unit="A",
    signed=True,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_battery_586 = SingleRegisterSensor(
    "Battery Temperature",
    586,
    0.1,
    offset=-100.0,
    mqtt_topic_suffix="battery/temperature",
    unit="°C",
    signed=False,
    groups=["deye_sg04lp3_battery"],
)

deye_sg04lp3_grid_625 = SingleRegisterSensor(
    "Total Grid Power", 625, 1, mqtt_topic_suffix="ac/total_power", unit="W", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_grid_598 = SingleRegisterSensor(
    "Grid Voltage L1", 598, 0.1, mqtt_topic_suffix="ac/l1/voltage", unit="V", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_grid_599 = SingleRegisterSensor(
    "Grid Voltage L2", 599, 0.1, mqtt_topic_suffix="ac/l2/voltage", unit="V", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_grid_600 = SingleRegisterSensor(
    "Grid Voltage L3", 600, 0.1, mqtt_topic_suffix="ac/l3/voltage", unit="V", signed=False, groups=["deye_sg04lp3"]
)

deye_sg04lp3_grid_604 = SingleRegisterSensor(
    "Internal CT L1 Power",
    604,
    1,
    mqtt_topic_suffix="ac/l1/ct/internal",
    unit="W",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_605 = SingleRegisterSensor(
    "Internal CT L2 Power",
    605,
    1,
    mqtt_topic_suffix="ac/l2/ct/internal",
    unit="W",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_606 = SingleRegisterSensor(
    "Internal CT L3 Power",
    606,
    1,
    mqtt_topic_suffix="ac/l3/ct/internal",
    unit="W",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_616 = SingleRegisterSensor(
    "External CT L1 Power",
    616,
    1,
    mqtt_topic_suffix="ac/l1/ct/external",
    unit="W",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_617 = SingleRegisterSensor(
    "External CT L2 Power",
    617,
    1,
    mqtt_topic_suffix="ac/l2/ct/external",
    unit="W",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_618 = SingleRegisterSensor(
    "External CT L3 Power",
    618,
    1,
    mqtt_topic_suffix="ac/l3/ct/external",
    unit="W",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_520 = SingleRegisterSensor(
    "Daily Energy Bought",
    520,
    0.1,
    mqtt_topic_suffix="ac/daily_energy_bought",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_522 = DoubleRegisterSensor(
    "Total Energy Bought",
    522,
    0.1,
    mqtt_topic_suffix="ac/total_energy_bought",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_521 = SingleRegisterSensor(
    "Daily Energy Sold",
    521,
    0.1,
    mqtt_topic_suffix="ac/daily_energy_sold",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_grid_524 = DoubleRegisterSensor(
    "Total Energy Sold",
    524,
    0.1,
    mqtt_topic_suffix="ac/total_energy_sold",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_upload_653 = SingleRegisterSensor(
    "Total Load Power",
    653,
    1,
    mqtt_topic_suffix="ac/ups/total_power",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_ups"],
)

deye_sg04lp3_upload_650 = SingleRegisterSensor(
    "Load L1 Power", 650, 1, mqtt_topic_suffix="ac/ups/l1/power", unit="W", signed=False, groups=["deye_sg04lp3_ups"]
)

deye_sg04lp3_upload_651 = SingleRegisterSensor(
    "Load L2 Power", 651, 1, mqtt_topic_suffix="ac/ups/l2/power", unit="W", signed=False, groups=["deye_sg04lp3_ups"]
)

deye_sg04lp3_upload_652 = SingleRegisterSensor(
    "Load L3 Power", 652, 1, mqtt_topic_suffix="ac/ups/l3/power", unit="W", signed=False, groups=["deye_sg04lp3_ups"]
)

deye_sg04lp3_upload_644 = SingleRegisterSensor(
    "Load Voltage L1",
    644,
    0.1,
    mqtt_topic_suffix="ac/ups/l1/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_ups"],
)

deye_sg04lp3_upload_645 = SingleRegisterSensor(
    "Load Voltage L2",
    645,
    0.1,
    mqtt_topic_suffix="ac/ups/l2/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_ups"],
)

deye_sg04lp3_upload_646 = SingleRegisterSensor(
    "Load Voltage L3",
    646,
    0.1,
    mqtt_topic_suffix="ac/ups/l3/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_ups"],
)

deye_sg04lp3_upload_526 = SingleRegisterSensor(
    "Daily Load Consumption",
    526,
    0.1,
    mqtt_topic_suffix="ac/ups/daily_energy",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_ups"],
)

deye_sg04lp3_upload_527 = DoubleRegisterSensor(
    "Total Load Consumption",
    527,
    0.1,
    mqtt_topic_suffix="ac/ups/total_energy",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_ups"],
)

deye_sg04lp3_inverter_630 = SingleRegisterSensor(
    "Current L1", 630, 0.01, mqtt_topic_suffix="ac/l1/current", unit="A", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_inverter_631 = SingleRegisterSensor(
    "Current L2", 631, 0.01, mqtt_topic_suffix="ac/l2/current", unit="A", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_inverter_632 = SingleRegisterSensor(
    "Current L3", 632, 0.01, mqtt_topic_suffix="ac/l3/current", unit="A", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_inverter_633 = SingleRegisterSensor(
    "Inverter L1 Power", 633, 1, mqtt_topic_suffix="ac/l1/power", unit="W", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_inverter_634 = SingleRegisterSensor(
    "Inverter L2 Power", 634, 1, mqtt_topic_suffix="ac/l2/power", unit="W", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_inverter_635 = SingleRegisterSensor(
    "Inverter L3 Power", 635, 1, mqtt_topic_suffix="ac/l3/power", unit="W", signed=True, groups=["deye_sg04lp3"]
)

deye_sg04lp3_inverter_540 = SingleRegisterSensor(
    "DC Temperature",
    540,
    0.1,
    offset=-100.0,
    mqtt_topic_suffix="radiator_temp",
    unit="°C",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_inverter_541 = SingleRegisterSensor(
    "AC Temperature",
    541,
    0.1,
    offset=-100.0,
    mqtt_topic_suffix="ac/temperature",
    unit="°C",
    signed=True,
    groups=["deye_sg04lp3"],
)

deye_sg04lp3_time_of_use_146 = SingleRegisterSensor(
    "Time of Use Weekly Selling Schedule",
    146,
    1,
    mqtt_topic_suffix="timeofuse/selling",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_148 = SingleRegisterSensor(
    "Time of Use Time 1",
    148,
    1,
    mqtt_topic_suffix="timeofuse/time/1",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_149 = SingleRegisterSensor(
    "Time of Use Time 2",
    149,
    1,
    mqtt_topic_suffix="timeofuse/time/2",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_150 = SingleRegisterSensor(
    "Time of Use Time 3",
    150,
    1,
    mqtt_topic_suffix="timeofuse/time/3",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_151 = SingleRegisterSensor(
    "Time of Use Time 4",
    151,
    1,
    mqtt_topic_suffix="timeofuse/time/4",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_152 = SingleRegisterSensor(
    "Time of Use Time 5",
    152,
    1,
    mqtt_topic_suffix="timeofuse/time/5",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_153 = SingleRegisterSensor(
    "Time of Use Time 6",
    153,
    1,
    mqtt_topic_suffix="timeofuse/time/6",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_154 = SingleRegisterSensor(
    "Time of Use Power 1",
    154,
    1,
    mqtt_topic_suffix="timeofuse/power/1",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_155 = SingleRegisterSensor(
    "Time of Use Power 2",
    155,
    1,
    mqtt_topic_suffix="timeofuse/power/2",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_156 = SingleRegisterSensor(
    "Time of Use Power 3",
    156,
    1,
    mqtt_topic_suffix="timeofuse/power/3",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_157 = SingleRegisterSensor(
    "Time of Use Power 4",
    157,
    1,
    mqtt_topic_suffix="timeofuse/power/4",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_158 = SingleRegisterSensor(
    "Time of Use Power 5",
    158,
    1,
    mqtt_topic_suffix="timeofuse/power/5",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_159 = SingleRegisterSensor(
    "Time of Use Power 6",
    159,
    1,
    mqtt_topic_suffix="timeofuse/power/6",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_160 = SingleRegisterSensor(
    "Time of Use Voltage 1",
    160,
    0.01,
    mqtt_topic_suffix="timeofuse/voltage/1",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_161 = SingleRegisterSensor(
    "Time of Use Voltage 2",
    161,
    0.01,
    mqtt_topic_suffix="timeofuse/voltage/2",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_162 = SingleRegisterSensor(
    "Time of Use Voltage 3",
    162,
    0.01,
    mqtt_topic_suffix="timeofuse/voltage/3",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_163 = SingleRegisterSensor(
    "Time of Use Voltage 4",
    163,
    0.01,
    mqtt_topic_suffix="timeofuse/voltage/4",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_164 = SingleRegisterSensor(
    "Time of Use Voltage 5",
    164,
    0.01,
    mqtt_topic_suffix="timeofuse/voltage/5",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_165 = SingleRegisterSensor(
    "Time of Use Voltage 6",
    165,
    0.01,
    mqtt_topic_suffix="timeofuse/voltage/6",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_166 = SingleRegisterSensor(
    "Time of Use SOC 1",
    166,
    1,
    mqtt_topic_suffix="timeofuse/soc/1",
    unit="%",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_167 = SingleRegisterSensor(
    "Time of Use SOC 2",
    167,
    1,
    mqtt_topic_suffix="timeofuse/soc/2",
    unit="%",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_168 = SingleRegisterSensor(
    "Time of Use SOC 3",
    168,
    1,
    mqtt_topic_suffix="timeofuse/soc/3",
    unit="%",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_169 = SingleRegisterSensor(
    "Time of Use SOC 4",
    169,
    1,
    mqtt_topic_suffix="timeofuse/soc/4",
    unit="%",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_170 = SingleRegisterSensor(
    "Time of Use SOC 5",
    170,
    1,
    mqtt_topic_suffix="timeofuse/soc/5",
    unit="%",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_171 = SingleRegisterSensor(
    "Time of Use SOC 6",
    171,
    1,
    mqtt_topic_suffix="timeofuse/soc/6",
    unit="%",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_172 = SingleRegisterSensor(
    "Time of Use Charge Enable 1",
    172,
    1,
    mqtt_topic_suffix="timeofuse/enabled/1",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_173 = SingleRegisterSensor(
    "Time of Use Charge Enable 2",
    173,
    1,
    mqtt_topic_suffix="timeofuse/enabled/2",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_174 = SingleRegisterSensor(
    "Time of Use Charge Enable 3",
    174,
    1,
    mqtt_topic_suffix="timeofuse/enabled/3",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_175 = SingleRegisterSensor(
    "Time of Use Charge Enable 4",
    175,
    1,
    mqtt_topic_suffix="timeofuse/enabled/4",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_176 = SingleRegisterSensor(
    "Time of Use Charge Enable 5",
    176,
    1,
    mqtt_topic_suffix="timeofuse/enabled/5",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_time_of_use_177 = SingleRegisterSensor(
    "Time of Use Charge Enable 6",
    177,
    1,
    mqtt_topic_suffix="timeofuse/enabled/6",
    unit="",
    signed=False,
    groups=["deye_sg04lp3_timeofuse"],
)

deye_sg04lp3_generator_661 = SingleRegisterSensor(
    "Phase voltage of Gen port A",
    661,
    0.1,
    mqtt_topic_suffix="ac/generator/a/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_662 = SingleRegisterSensor(
    "Phase voltage of Gen port B",
    662,
    0.1,
    mqtt_topic_suffix="ac/generator/b/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_663 = SingleRegisterSensor(
    "Phase voltage of Gen port C",
    663,
    0.1,
    mqtt_topic_suffix="ac/generator/c/voltage",
    unit="V",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_664 = SingleRegisterSensor(
    "Phase power of Gen port A",
    664,
    1,
    mqtt_topic_suffix="ac/generator/a/power",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_665 = SingleRegisterSensor(
    "Phase power of Gen port B",
    665,
    1,
    mqtt_topic_suffix="ac/generator/b/power",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_666 = SingleRegisterSensor(
    "Phase power of Gen port C",
    666,
    1,
    mqtt_topic_suffix="ac/generator/c/power",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_667 = SingleRegisterSensor(
    "Total Power of Gen Ports",
    667,
    1,
    mqtt_topic_suffix="ac/generator/total_power",
    unit="W",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_generator_536 = SingleRegisterSensor(
    "Daily Generator Production",
    536,
    0.1,
    mqtt_topic_suffix="ac/generator/daily_energy",
    unit="kWh",
    signed=False,
    groups=["deye_sg04lp3_generator"],
)

deye_sg04lp3_sensors = [
    deye_sg04lp3_solar_672,
    deye_sg04lp3_solar_673,
    deye_sg04lp3_solar_676,
    deye_sg04lp3_solar_678,
    deye_sg04lp3_solar_677,
    deye_sg04lp3_solar_679,
    deye_sg04lp3_solar_529,
    deye_sg04lp3_solar_534,
    deye_sg04lp3_battery_514,
    deye_sg04lp3_battery_515,
    deye_sg04lp3_battery_516,
    deye_sg04lp3_battery_518,
    deye_sg04lp3_battery_590,
    deye_sg04lp3_battery_587,
    deye_sg04lp3_battery_588,
    deye_sg04lp3_battery_591,
    deye_sg04lp3_battery_586,
    deye_sg04lp3_grid_625,
    deye_sg04lp3_grid_598,
    deye_sg04lp3_grid_599,
    deye_sg04lp3_grid_600,
    deye_sg04lp3_grid_604,
    deye_sg04lp3_grid_605,
    deye_sg04lp3_grid_606,
    deye_sg04lp3_grid_616,
    deye_sg04lp3_grid_617,
    deye_sg04lp3_grid_618,
    deye_sg04lp3_grid_520,
    deye_sg04lp3_grid_522,
    deye_sg04lp3_grid_521,
    deye_sg04lp3_grid_524,
    deye_sg04lp3_upload_653,
    deye_sg04lp3_upload_650,
    deye_sg04lp3_upload_651,
    deye_sg04lp3_upload_652,
    deye_sg04lp3_upload_644,
    deye_sg04lp3_upload_645,
    deye_sg04lp3_upload_646,
    deye_sg04lp3_upload_526,
    deye_sg04lp3_upload_527,
    deye_sg04lp3_inverter_630,
    deye_sg04lp3_inverter_631,
    deye_sg04lp3_inverter_632,
    deye_sg04lp3_inverter_633,
    deye_sg04lp3_inverter_634,
    deye_sg04lp3_inverter_635,
    deye_sg04lp3_inverter_540,
    deye_sg04lp3_inverter_541,
    deye_sg04lp3_time_of_use_146,
    deye_sg04lp3_time_of_use_148,
    deye_sg04lp3_time_of_use_149,
    deye_sg04lp3_time_of_use_150,
    deye_sg04lp3_time_of_use_151,
    deye_sg04lp3_time_of_use_152,
    deye_sg04lp3_time_of_use_153,
    deye_sg04lp3_time_of_use_154,
    deye_sg04lp3_time_of_use_155,
    deye_sg04lp3_time_of_use_156,
    deye_sg04lp3_time_of_use_157,
    deye_sg04lp3_time_of_use_158,
    deye_sg04lp3_time_of_use_159,
    deye_sg04lp3_time_of_use_160,
    deye_sg04lp3_time_of_use_161,
    deye_sg04lp3_time_of_use_162,
    deye_sg04lp3_time_of_use_163,
    deye_sg04lp3_time_of_use_164,
    deye_sg04lp3_time_of_use_165,
    deye_sg04lp3_time_of_use_166,
    deye_sg04lp3_time_of_use_167,
    deye_sg04lp3_time_of_use_168,
    deye_sg04lp3_time_of_use_169,
    deye_sg04lp3_time_of_use_170,
    deye_sg04lp3_time_of_use_171,
    deye_sg04lp3_time_of_use_172,
    deye_sg04lp3_time_of_use_173,
    deye_sg04lp3_time_of_use_174,
    deye_sg04lp3_time_of_use_175,
    deye_sg04lp3_time_of_use_176,
    deye_sg04lp3_time_of_use_177,
    deye_sg04lp3_generator_661,
    deye_sg04lp3_generator_662,
    deye_sg04lp3_generator_663,
    deye_sg04lp3_generator_664,
    deye_sg04lp3_generator_665,
    deye_sg04lp3_generator_666,
    deye_sg04lp3_generator_667,
    deye_sg04lp3_generator_536,
]

deye_sg04lp3_register_ranges = [
    SensorRegisterRange(group="deye_sg04lp3", first_reg_address=514, last_reg_address=558),
    SensorRegisterRange(group="deye_sg04lp3_ups", first_reg_address=514, last_reg_address=558),
    SensorRegisterRange(group="deye_sg04lp3_battery", first_reg_address=514, last_reg_address=558),
    SensorRegisterRange(group="deye_sg04lp3_generator", first_reg_address=514, last_reg_address=558),
    SensorRegisterRange(group="deye_sg04lp3_battery", first_reg_address=586, last_reg_address=591),
    SensorRegisterRange(group="deye_sg04lp3", first_reg_address=598, last_reg_address=636),
    SensorRegisterRange(group="deye_sg04lp3_ups", first_reg_address=644, last_reg_address=653),
    SensorRegisterRange(group="deye_sg04lp3", first_reg_address=672, last_reg_address=679),
    SensorRegisterRange(group="deye_sg04lp3_timeofuse", first_reg_address=146, last_reg_address=177),
    SensorRegisterRange(group="deye_sg04lp3_generator", first_reg_address=661, last_reg_address=667),
]
